title: 
author: Hikaru Nguyen
description: おはいよう＾＾

highlighter: null
permalink: /:title

url: http://hikarunguyen.xyz
baseurl: 

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: ruby
