title: 
author: Hikaru Nguyen
description: おはいよう＾＾

highlighter: null
permalink: /:title

url: hikarunguyen.xyz
baseurl: /hikarunguyen.xyz

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: ruby
